### ISSUE TITLE
NullPointerException，java.lang.String.endsWith(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/okhttp-RxHttp#108]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
        at rxhttp.wrapper.param.RxHttp.addDomainIfAbsent(RxHttp.java:498)
        at rxhttp.wrapper.param.RxHttp.addDefaultDomainIfAbsent(RxHttp.java:489)
        at rxhttp.wrapper.param.RxHttp.asParser(RxHttp.java:378)
        at rxhttp.wrapper.param.RxHttp.asResultListPaser(RxHttp.java:438)
不知道为什么会这样？Url没有写错啊

**Comment by liujingxing** [comment]
@DefaultDomain注解标注的url为null

**Comment by chenyinchao** [comment]
@DefaultDomain标注的url我是直接写固定的，可是有的请求可以成功，有的请求抛g.endsWith(java.lang.String)' on a null object reference

**Comment by chenyinchao** [comment]
@liujingxing 
@DefaultDomain标注的url我是直接写固定的，可是有的请求可以成功，有的请求抛g.endsWith(java.lang.String)' on a null object reference

**Comment by liujingxing** [comment]
??最后解决了？什么问题？
