### ISSUE TITLE
请教下，rebuild报错 A comparison has not been followed by an if

### ISSUE THREAD

**Issue by YistXin** [liujingxing/okhttp-RxHttp#114]
Rebuild时报错A comparison has not been followed by an if
有解决办法吗

**Comment by liujingxing** [comment]
仅凭这些信息看不出啥问题，有更详细的日志吗？

**Comment by YistXin** [comment]
@liujingxing 
java.lang.RuntimeException: java.lang.AssertionError: A comparison has not been followed by an if
	at com.android.sched.util.config.ReflectFactory.create(ReflectFactory.java:98)
	at com.android.jack.Jack.buildSession(Jack.java:1035)
	at com.android.jack.Jack.run(Jack.java:550)
	at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:124)
	at com.android.builder.core.JackToolchain.convertUsingJackApis(JackToolchain.java:310)
	at com.android.builder.core.JackToolchain.convertUsingApis(JackToolchain.java:189)
	at com.android.builder.core.JackToolchain.convert(JackToolchain.java:170)
	at com.android.builder.internal.compiler.JackConversionCache.convertLibrary(JackConversionCache.java:106)
	at com.android.build.gradle.tasks.JackPreDexTransform.runJack(JackPreDexTransform.java:205)
	at com.android.build.gradle.tasks.JackPreDexTransform.transform(JackPreDexTransform.java:161)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: A comparison has not been followed by an if
	at com.android.jill.frontend.java.MethodBodyWriter.writeBody(MethodBodyWriter.java:603)
	at com.android.jill.frontend.java.MethodBodyWriter.writeJavaMethodBody(MethodBodyWriter.java:474)
	at com.android.jill.frontend.java.MethodBodyWriter.writeMethodBody(MethodBodyWriter.java:415)
	at com.android.jill.frontend.java.MethodBodyWriter.writeMethod(MethodBodyWriter.java:345)
	at com.android.jill.frontend.java.MethodBodyWriter.write(MethodBodyWriter.java:272)
	at com.android.jill.frontend.java.ClassNodeWriter.writeMethods(ClassNodeWriter.java:304)
	at com.android.jill.frontend.java.ClassNodeWriter.writeClass(ClassNodeWriter.java:106)
	at com.android.jill.frontend.java.ClassNodeWriter.write(ClassNodeWriter.java:69)
	at com.android.jill.frontend.java.JavaTransformer.transform(JavaTransformer.java:275)
	at com.android.jill.frontend.java.JavaTransformer.transformToVFS(JavaTransformer.java:256)
	at com.android.jill.frontend.java.JavaTransformer.transformJavaFiles(JavaTransformer.java:243)
	at com.android.jill.frontend.java.JavaTransformer.transform(JavaTransformer.java:162)
	at com.android.jill.Jill.process(Jill.java:55)
	at com.android.jack.incremental.CommonFilter.convertJarWithJill(CommonFilter.java:403)
	at com.android.jack.incremental.CommonFilter.getImportedLibraries(CommonFilter.java:303)
	at com.android.jack.incremental.NoInputFilter.<init>(NoInputFilter.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.android.sched.util.config.ReflectFactory.create(ReflectFactory.java:90)
	... 60 more

**Comment by YistXin** [comment]
@liujingxing 有没有可能是配置jackOptions 的问题？  我的工程配置compileOptions JavaVersion.VERSION_1_8之后，需要配置jackOption才能用。

**Comment by YistXin** [comment]
这是我的gradle配置。
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "com.xxx.xxx"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0.32"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        jackOptions {
            enabled true
        }

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [rxhttp_okhttp: '4.7.2']
            }
        }

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    repositories {
        flatDir {
            dirs 'libs'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:27.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'

    compile 'com.ljx.rxhttp:rxhttp:2.2.7'
    compile 'com.squareup.okhttp3:okhttp:4.7.2'
    annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.2.7'
}
`

**Comment by liujingxing** [comment]
没看出这个跟rxhttp有什么关系。可能需要你自己再查查

**Comment by YistXin** [comment]
好的， 这个issue可否open一段时间？ 如果我解决了可以给其他遇到相同问题的人看到。
