### ISSUE TITLE
响应结果解析转换错误

### ISSUE THREAD

**Issue by jingzhanwu** [liujingxing/okhttp-RxHttp#120]
我使用的默认配置gson解析响应数据，也自定义了Parser，如下

@Parser(name = "Response", wrappers = {List.class, PageList.class})
public class ResponseParser<T> extends AbstractParser<T> {

    /**
     * 此构造方法适用于任意Class对象，但更多用于带泛型的Class对象，如：List<Student>
     * <p>
     * 用法:
     * Java: .asParser(new ResponseParser<List<Student>>(){})
     * Kotlin: .asParser(object : ResponseParser<List<Student>>() {})
     * <p>
     * 注：此构造方法一定要用protected关键字修饰，否则调用此构造方法将拿不到泛型类型
     */
    protected ResponseParser() {
        super();
    }

    /**
     * 此构造方法仅适用于不带泛型的Class对象，如: Student.class
     * <p>
     * 用法
     * Java: .asParser(new ResponseParser<>(Student.class))   或者  .asResponse(Student.class)
     * Kotlin: .asParser(ResponseParser(Student::class.java)) 或者  .asResponse(Student::class.java)
     */
    public ResponseParser(Type type) {
        super(type);
    }

    @Override
    public T onParse(@NotNull Response response) throws IOException {
        //获取泛型类型
        final Type type = ParameterizedTypeImpl.get(Response.class, mType);
        HttpResponse<T> data = convert(response, type);
        //获取data字段
        T t = data.getData();
        if (t == null && mType == String.class) {
            /*
             * 考虑到有些时候服务端会返回：{"errorCode":0,"errorMsg":"关注成功"}  类似没有data的数据
             * 此时code正确，但是data字段为空，直接返回data的话，会报空指针错误，
             * 所以，判断泛型为String类型时，重新赋值，并确保赋值不为null
             */
            t = (T) data.getMessage();
        }
        //code不等于0，说明数据不正确，抛出异常
        if (data.getCode() != 0 || t == null) {
            throw new ParseException(String.valueOf(data.getCode()), data.getMessage(), response);
        }
        return t;
    }
}

HttpResponse类是我的结构返回结构：
public class HttpResponse<T> implements Serializable {
    private int code;
    private String message;
    private T data;

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }
}

发起请求如下：

RxHttp.postJson("/api/system/login/login")
                .add("loginName", username)
                .add("password", password)
                .add("clientType", "android")
                .asResponse(LoginUserEntry.class)
                .subscribe(user -> {

                }, (OnError) error -> {

                });

报错信息如下：
2020-06-28 15:58:09.946 27156-27324/com.mti.km.security W/System.err: java.lang.ClassCastException: okhttp3.Response cannot be cast to com.mti.km.security.data.bean.HttpResponse
2020-06-28 15:58:09.946 27156-27324/com.mti.km.security W/System.err:     at com.mti.km.security.parser.ResponseParser.onParse(ResponseParser.java:58)
2020-06-28 15:58:09.946 27156-27324/com.mti.km.security W/System.err:     at rxhttp.ObservableHttp.execute(ObservableHttp.java:109)
2020-06-28 15:58:09.946 27156-27324/com.mti.km.security W/System.err:     at rxhttp.ObservableHttp.subscribeActual(ObservableHttp.java:58)
2020-06-28 15:58:09.946 27156-27324/com.mti.km.security W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2020-06-28 15:58:09.946 27156-27324/com.mti.km.security W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2020-06-28 15:58:09.946 27156-27324/com.mti.km.security W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2020-06-28 15:58:09.946 27156-27324/com.mti.km.security W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2020-06-28 15:58:09.947 27156-27324/com.mti.km.security W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2020-06-28 15:58:09.947 27156-27324/com.mti.km.security W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-28 15:58:09.947 27156-27324/com.mti.km.security W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020-06-28 15:58:09.947 27156-27324/com.mti.km.security W/System.err:     at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
2020-06-28 15:58:09.947 27156-27324/com.mti.km.security W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
2020-06-28 15:58:09.947 27156-27324/com.mti.km.security W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-06-28 15:58:09.947 27156-27324/com.mti.km.security W/System.err:     at java.lang.Thread.run(Thread.java:784)
2020-06-28 15:58:09.947 27156-27324/com.mti.km.security E/RxHttp: java.lang.ClassCastException: okhttp3.Response cannot be cast to com.mti.km.security.data.bean.HttpResponse
    
    https://xx.xx.xx:443/api/system/login/login
2020-06-28 15:58:09.949 27156-27324/com.mti.km.security E/RxJava: io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
2020-06-28 15:58:09.958 27156-27236/com.mti.km.security W/libEGL: EGLNativeWindowType 0x7dc075a010 disconnect failed
2020-06-28 15:58:10.004 27156-27156/com.mti.km.security W/InputMethodManager: startInputReason = 1

请问是哪里配置出错了

**Comment by liujingxing** [comment]
`ParameterizedTypeImpl.get(Response.class, mType)`   改成  `ParameterizedTypeImpl.get(HttpResponse.class, mType)`，ParameterizedTypeImpl类用法查看https://juejin.im/post/5cbd5986f265da035e2124a2

**Comment by jingzhanwu** [comment]
为什么我的onNext，和onError同时都有结果返回
.subscribe(user -> {

            }, (OnError) error -> {

            });

**Comment by liujingxing** [comment]
onNext回调里面发生的Exception异常会被捕获，此时就将异常带上，走失败回调

**Comment by jingzhanwu** [comment]
rxhttp-compiler可以同时使用 kpt 和annotationProcessor吗

**Comment by liujingxing** [comment]
同一个module，kapt/annotationProcessor二选一，annotationProcessor检索不kotlin编写的类，只要项目使用了kotlin，都建议使用kapt

**Comment by jingzhanwu** [comment]
好的，谢谢了
