### ISSUE TITLE
使用postJson报错：write javaBean error, fastjson version 1.2.71, class com.google.gson.JsonPrimitive, fieldName : apiName

### ISSUE THREAD

**Issue by Alexxiaopang** [liujingxing/okhttp-RxHttp#133]
版本：
    implementation 'com.ljx.rxhttp:rxhttp:2.2.7'
    kapt 'com.ljx.rxhttp:rxhttp-compiler:2.2.7' 
    implementation 'com.ljx.rxlife:rxlife-coroutine:2.0.0'
    implementation 'com.ljx.rxhttp:converter-fastjson:2.2.7'

使用addAll添加：
"{\"apiName\":\"expertInfo\",\"channel\":2001001,\"memberId\":15,\"platform\":2,\"uniqueNo\":\"qazwsx-rtyu-1234-tt-2\",\"vt\":\"1.0\"}"

直接报错
write javaBean error, fastjson version 1.2.71, class com.google.gson.JsonPrimitive, fieldName : apiName

使用JSON.toJSONString(TestBean())也是同样的错误，能请问一下这是什么问题么？

**Comment by Alexxiaopang** [comment]
经过调试，是由于设置了全局解析器导致的： RxHttp.setConverter(FastJsonConverter.create());
使用demo也是一样的报错
现在不能直接设置全局解析器？

**Comment by liujingxing** [comment]
详细错误日志发出来

**Comment by liujingxing** [comment]
初步看是反序列化的时候出错的，对比下apiName字段类型是否一致

**Comment by Alexxiaopang** [comment]
这个错误在提供的Demo也会出现的，只要把全局fastjson解析打开



------------------ 原始邮件 ------------------
发件人: liujingxing <notifications@github.com&gt;
发送时间: 2020年7月28日 12:13
收件人: liujingxing/okhttp-RxHttp <okhttp-RxHttp@noreply.github.com&gt;
抄送: Alexxiaopang <610611029@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[liujingxing/okhttp-RxHttp] 使用postJson报错：write javaBean error, fastjson version 1.2.71, class com.google.gson.JsonPrimitive, fieldName : apiName (#133)





 
初步看是反序列化的时候出错的，对比下apiName字段类型是否一致

**Comment by Alexxiaopang** [comment]
等下我发一下，复现步骤可以拿Demo的RxhttpManager的全局fastjson解析打开，然后去kotlin协程页面，直接请求



------------------ 原始邮件 ------------------
发件人: liujingxing <notifications@github.com&gt;
发送时间: 2020年7月28日 12:09
收件人: liujingxing/okhttp-RxHttp <okhttp-RxHttp@noreply.github.com&gt;
抄送: Alexxiaopang <610611029@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[liujingxing/okhttp-RxHttp] 使用postJson报错：write javaBean error, fastjson version 1.2.71, class com.google.gson.JsonPrimitive, fieldName : apiName (#133)





 
详细错误日志发出来

**Comment by liujingxing** [comment]
我试过Demo了，全局fastjson打开没问题

**Comment by Alexxiaopang** [comment]
感谢回复，我拉取的是demo的代码，没做修改，然后把RxHttpManager的  RxHttp.setConverter(FastJsonConverter.create());打开

去到首页，使用Rxjava或者协程 的 postJson请求，就会出现序列化的问题

机型：小米9  安卓10 miui12

底下是demo全部log：
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err: com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.61, class com.google.gson.JsonPrimitive, fieldName : height
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:530)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:825)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:796)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:789)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.JSON.toJSONBytes(JSON.java:764)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at rxhttp.wrapper.converter.FastJsonConverter.convert(FastJsonConverter.java:62)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at rxhttp.wrapper.param.AbstractParam.convert(AbstractParam.java:227)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at rxhttp.wrapper.param.JsonParam.getRequestBody(JsonParam.java:38)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at rxhttp.wrapper.utils.BuildUtil.buildRequest(BuildUtil.java:30)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at rxhttp.wrapper.param.AbstractParam.buildRequest(AbstractParam.java:212)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at rxhttp.wrapper.param.ObservableHttp.execute(ObservableHttp.java:81)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at rxhttp.wrapper.param.ObservableHttp.subscribeActual(ObservableHttp.java:58)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:589)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
2020-07-28 12:38:35.847 11055-11104/com.example.rxhttp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err: Caused by: java.lang.IllegalStateException: Not a JSON Array: 180
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.util.FieldInfo.get(FieldInfo.java:491)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.serializer.FieldSerializer.getPropertyValueDirect(FieldSerializer.java:149)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err:     at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:293)
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp W/System.err: 	... 25 more
2020-07-28 12:38:35.848 11055-11104/com.example.rxhttp E/RxHttp: com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.2.61, class com.google.gson.JsonPrimitive, fieldName : height
    
    https://www.wanandroid.com/article/list/0/json
2020-07-28 12:38:35.866 11055-11055/com.example.rxhttp I/Toast: Show toast from OpPackageName:com.example.rxhttp, PackageName:com.example.rxhttp

**Comment by Alexxiaopang** [comment]
补充一下：AS的版本是4.0.0

**Comment by liujingxing** [comment]
知道问题，目前你可以通过自定义Param，重写addAll方法，解决此问题

**Comment by Alexxiaopang** [comment]
好的，感谢了，也希望后续可以修复，能提一个建议么，后续postJson可以加入add(object)功能么，感觉body的bean类需要再转一次stringObj才能添加进去

**Comment by liujingxing** [comment]
近期会修复，你可以通过map替代bean类，随后通过addAll(Map)方法添加参数

**Comment by Alexxiaopang** [comment]
好的，打扰了，我通过拓展函数添加了多个方法，没有重写Param也可以

**Comment by liujingxing** [comment]
v2.3.2版本已修复该问题
