### ISSUE TITLE
换成 https 报错：javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xb2e3bf00: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/okhttp-RxHttp#149]
javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xb2e3bf00: I/O error during system call, Connection reset by peer
at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:367)
at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:325)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:197)
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)

版本: rxhttp : "1.4.0",
rxlife : "1.1.0",
okhttp : "3.12.6",
把RxHttp请求从http改成https报错，这个怎么解决呢

**Comment by liujingxing** [comment]
自己是否有配置过`OkHttpClient`对象？有的话，贴出来。如果没有，请按如下配置：
```java
SSLParams sslParams = HttpsUtils.getSslSocketFactory();                                       
OkHttpClient client = new OkHttpClient.Builder()                                              
    .connectTimeout(10, TimeUnit.SECONDS)                                                     
    .readTimeout(10, TimeUnit.SECONDS)                                                        
    .writeTimeout(10, TimeUnit.SECONDS)                                                       
    .sslSocketFactory(sslParams.sSLSocketFactory, sslParams.trustManager) //添加信任证书            
    .hostnameVerifier((hostname, session) -> true) //忽略host验证                                 
    .build();                                                                                 
//RxHttp初始化，自定义OkHttpClient对象，非必须                                                             
RxHttp.init(client, BuildConfig.DEBUG);                                                       
```
其中HttpsUtils类，在新版本中已集成。你1.4.0版本的话，自己去Demo找一下这个类。


经过以上配置还不行的话，自己先用postman试试。
