### ISSUE TITLE
编译成功后无法运行：NoSuchMethodError

### ISSUE THREAD

**Issue by YRowis** [liujingxing/okhttp-RxHttp#161]
```
  RxHttp.init(null, true);
  RxHttp.get("http://www.baidu.com")
                .asString()
                .subscribe(s -> {
                    //请求成功
                }, throwable -> {
                    //请求失败
                });

```
...as的编译已经通过。运行后
```
java.lang.NoSuchMethodError: No static method copyInto([B[BIII)[B in class Lkotlin/collections/ArraysKt; or its super classes (declaration of 'kotlin.collections.ArraysKt' appears in /data/app/com.test.test-2/base.apk)
     at rxhttp.RxHttp.<init>(RxHttp.java:72)
        at rxhttp.RxHttpNoBodyParam.<init>(RxHttpNoBodyParam.java:17)
        at rxhttp.RxHttp.with(RxHttp.java:251)
        at rxhttp.RxHttp.get(RxHttp.java:195)
        at com.ly.txb.ui.mainActivity.MainActivity.initObserver(MainActivity.java:60)
```
还是我没

**Comment by liujingxing** [comment]
RxHttp、OkHttp版本分别多少？rxhttp、rxhttp-compiler版本要保持同步

**Comment by YRowis** [comment]
```
    //以下3个为必须，
    implementation 'com.ljx.rxhttp:rxhttp:2.4.0'
    implementation 'com.squareup.okhttp3:okhttp:4.8.1' 
    annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.4.0' 

    implementation 'com.ljx.rxlife:rxlife-coroutine:2.0.1' 
    //rxjava3
    implementation 'io.reactivex.rxjava3:rxjava:3.0.2'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation 'com.ljx.rxlife3:rxlife-rxjava:3.0.0' 
```

**Comment by liujingxing** [comment]
看日志，跟kotlin有关系，项目是否有依赖kotlin？`annotationProcessorOptions`中传的参数也发出来看看

**Comment by YRowis** [comment]
```
 annotationProcessorOptions {
                arguments = [
                        //必须，告知RxHttp你依赖的okhttp版本，目前已适配 v3.12.0 - v4.8.1版本  (v4.3.0除外)
                        rxhttp_okhttp : '4.8.1',
                        //使用asXxx方法时必须，告知RxHttp你依赖的rxjava版本，可传入rxjava2、rxjava3
                        rxhttp_rxjava : 'rxjava3',
//                        rxhttp_package: 'rxhttp'   //非必须，指定RxHttp类包名
                ]
```
            }

**Comment by YRowis** [comment]
应该是     configurations.all {
            Configuration configuration ->

**Comment by liujingxing** [comment]
初步看，并未发现啥问题。个人猜测跟okhttp版本有关系，检查下是否有依赖多个okhttp 版本，可能其它第三方库也依赖了okhttp。检查下来没解决的话，可以加我QQ 327744707，把Demo发我看看。

**Comment by YRowis** [comment]
已解决，是引用库带有kotlin或自身kotlin版本导致。我指定版本确没有及时更新版本号，就会有方法函数找不到，以后要在最后清空后查看添加。谢谢大佬的及时帮助。
```
     configurations.all {
            Configuration configuration ->
                //当遇到版本冲突时直接构建失败
                configuration.resolutionStrategy.failOnVersionConflict()
                //指定版本，避免冲突
               ......
                configuration.resolutionStrategy.force(['org.jetbrains.kotlin:kotlin-stdlib:1.4.0'])
                configuration.resolutionStrategy.force(['org.jetbrains.kotlin:kotlin-stdlib-common:1.4.0'])
                configuration.resolutionStrategy.force(['io.reactivex.rxjava3:rxjava:3.0.0'])
                configuration.resolutionStrategy.force(['org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.4.0'])

        }
```

**Comment by liujingxing** [comment]
客气，感谢支持
