### ISSUE TITLE
下载视频获取不到进度

### ISSUE THREAD

**Issue by pejiang** [liujingxing/okhttp-RxHttp#167]
下载视频进度不更新，只有在视频下载完成后会更新2次，并且返回的totalsize=-1

**Comment by liujingxing** [comment]
`RxHttp.setDebug(true)`开启调试模式，然后日志过来RxHttp，检查响应头里是否有`Transfer-Encoding: chunked`，有的话，该下载链接，就不支持下载进度回调，因为读取不到文件总size。

**Comment by pejiang** [comment]
> `RxHttp.setDebug(true)`开启调试模式，然后日志过滤RxHttp，检查响应头里是否有`Transfer-Encoding: chunked`，有的话，该下载链接，就不支持下载进度回调，因为读取不到文件总size。

有这个头，如果是这样的话需要怎么处理，需要改后端吗

**Comment by liujingxing** [comment]
需要后端在响应头里返回`Content-Length`字段，以读取到文件总size，`Content-Length`与`Transfer-Encoding`是互斥的。

**Comment by pejiang** [comment]
> 需要后端在响应头里返回`Content-Length`字段，以读取到文件总size，`Content-Length`与`Transfer-Encoding`是互斥的。

好的，十分感谢。

另外一个问题，我把库更新到了最新版，发现修改了一些api，没办法在主线程更新ui
这是修改后的调用
RxHttp.postForm(url)
                .asDownload(file.getAbsolutePath(), progress -> {
                    d(progress.toString());
                    if (progress.getProgress() == 100) {
                        pass
                    } else
                        updateDownloadProgress(file.getName(), (int) (progress.getTotalSize() / 1024), (int) (progress.getCurrentSize() / 1024));
                })
                .subscribeOn(AndroidSchedulers.mainThread())
                .subscribe(s -> {
                    d(s);
                }, throwable -> {
                    closeDownloadProgress();
                    e(throwable.toString());
                })

**Comment by liujingxing** [comment]
调用`asDownload(String, Scheduler, Consumer<Progress>)`方法，第二个参数就是切换线程的

**Comment by pejiang** [comment]
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
java.io.IOException: canceled due to java.lang.IllegalStateException: closed 新版本下载发生这个问题，从网上搜索都是body().toString()调用多次，但是下载没有调用过response.body().string();

**Comment by liujingxing** [comment]
这个需要根据你的代码去查找原因，什么情况下会出现？

**Comment by pejiang** [comment]
> 这个需要根据你的代码去查找原因，什么情况下会出现？

RxHttp.postForm(url)
.asDownload(file.getAbsolutePath(), progress -> {
d(progress.toString());
if (progress.getProgress() == 100) {
pass
} else
updateDownloadProgress(file.getName(), (int) (progress.getTotalSize() / 1024), (int) (progress.getCurrentSize() / 1024));
})
.subscribeOn(AndroidSchedulers.mainThread())
.subscribe(s -> {
d(s);
}, throwable -> {
closeDownloadProgress();
e(throwable.toString());
})

代码就是这段，没找到规律，我先切换的旧版本了，项目比较急

**Comment by liujingxing** [comment]
把错误堆栈信息发出来

**Comment by pejiang** [comment]
> 把错误堆栈信息发出来

------------------crash----------------------
BOARD=unknown
crashTime=2020-10-16 03:22:14
CPU_ABI2=
HOST=49cfa9ee5067
versionName=5.2
IS_TREBLE_ENABLED=false
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@1bd1dc8
CPU_ABI=x86
PERMISSIONS_REVIEW_REQUIRED=false
IS_USERDEBUG=true
DISPLAY=vbox86p-userdebug 8.1.0 OPM6.171019.030.E1 448 test-keys
SUPPORTED_ABIS=[Ljava.lang.String;@d48ce61
FINGERPRINT=Android/vbox86p/vbox86p:8.1.0/OPM6.171019.030.E1/448:userdebug/test-keys
PRODUCT=vbox86p
ID=OPM6.171019.030.E1
TYPE=userdebug
SERIAL=unknown
IS_CONTAINER=false
IS_ENG=false
DEVICE=vbox86p
TIME=1591939118000
IS_USER=false
MODEL=Custom Tablet
MANUFACTURER=unknown
USER=genymotion
versionCode=10
BRAND=Android
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@bf2fe6b
HARDWARE=vbox86
IS_DEBUGGABLE=true
BOOTLOADER=unknown
RADIO=unknown
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=true
TAGS=test-keys
java.lang.IllegalStateException: closed
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:263)
	at okio.ForwardingSink.flush(ForwardingSink.kt:32)
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:269)
	at rxhttp.wrapper.progress.ProgressRequestBody.writeTo(ProgressRequestBody.java:78)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at rxhttp.wrapper.intercept.CacheInterceptor.intercept(CacheInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

-------------------end-----------------------

**Comment by liujingxing** [comment]
加我QQ  327744707
