### ISSUE TITLE
关于cookie的几个问题

### ISSUE THREAD

**Issue by 932707629** [liujingxing/okhttp-RxHttp#172]
rxhttp版本:2.4.1
okhttp版本:4.7.2

cookie设置
`OkHttpClient.Builder()
            .cookieJar(CookieStore(File(ctx.externalCacheDir,"RxhttpCookie"))).build()`

读取写入cookie
```
val iCookieJar = HttpSender.getOkHttpClient().cookieJar as ICookieJar
            val httpUrl = "https://www.wanandroid.com/".toHttpUrlOrNull()
            val cookieStr = "JSESSIONID=6B1B904EC42DFFFFDB3AEA299DA13AC2; Path=/; Secure; HttpOnly"
            val cookie=Cookie.parse(httpUrl!!, cookieStr) //通过parse方法构造Cookie对象，也可以通过构造器构造
            iCookieJar.saveCookie(httpUrl, cookie)
        println("缓存cookie成功${cookieStr}==${httpUrl}==${cookie}");

        println("打印一下缓存的cookie${JSONObject.toJSONString(iCookieJar.loadCookie(httpUrl))}");
```

1. 手动缓存cookie 然后再查询对应的cookie差不到  返回空数组
2. 清除缓存之后 再手动缓存cookie会报FileNotFoundException

**Comment by 932707629** [comment]
跟踪了下代码  第一个返回空数组应该是fastjson的问题

**Comment by liujingxing** [comment]
第一个问题是fastjson的问题，直接`val loadCookie = iCookieJar.loadCookie(httpUrl)`是有值的；
第二个问题，我试过了，没发现问题，你可以把具体异常发出来看看。

**Comment by 932707629** [comment]
```
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.soushin.ddm/cache/DDMCookie/journal.bkp: open failed: ENOENT (No such file or directory)
     at libcore.io.IoBridge.open(IoBridge.java:456)
     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
     at okio.Okio__JvmOkioKt.sink(JvmOkio.kt:170)
     at okio.Okio.sink(Unknown Source)
     at okio.Okio__JvmOkioKt.sink$default(JvmOkio.kt:170)
     at okio.Okio.sink$default(Unknown Source)
     at okhttp3.internal.io.FileSystem$Companion$SYSTEM$1.sink(FileSystem.kt:58)
     at okhttp3.internal.Util.isCivilized(Util.kt:532)
     at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.kt:231)
     at okhttp3.internal.cache.DiskLruCache.edit(DiskLruCache.kt:449)
     at okhttp3.internal.cache.DiskLruCache.edit$default(DiskLruCache.kt:448)
     at okhttp3.internal.cache.DiskLruCache.edit(DiskLruCache.kt)
     at com.soushin.ddm.network.DDMCookieStore.saveDdmCookie(DDMCookieStore.java:132)
     at com.soushin.ddm.config.AppData.syncUserCookie(AppData.kt:141)
     at com.soushin.ddm.mvvm.viewmodel.SettingViewModel.onItemClick(SettingViewModel.kt:57)
     at com.soushin.ddm.mvvm.ui.SettingActivity$initData$1.onItemClick(SettingActivity.kt:52)
     at com.chad.library.adapter.base.BaseQuickAdapter.setOnItemClick(BaseQuickAdapter.kt:596)
     at com.chad.library.adapter.base.BaseQuickAdapter$bindViewClickListener$$inlined$let$lambda$1.onClick(BaseQuickAdapter.kt:538)
     at android.view.View.performClick(View.java:4780)
     at android.view.View$PerformClick.run(View.java:19866)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5254)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
 Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
     at libcore.io.Posix.open(Native Method)
     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
     at libcore.io.IoBridge.open(IoBridge.java:442)
 	... 27 more
```

以上是异常信息  因为现有的CookieStore不满足业务需求 所以就自定义了一个DDMCookieStore（新增了saveDdmCookie()这个方法，方法实现和原来的saveCookie()一样，原来的saveCookie()我给注释掉了）

**Comment by liujingxing** [comment]
你是怎么清楚缓存的？

**Comment by liujingxing** [comment]
用`CookieStore#saveCookie` 方法试试会不会有问题，如果没有的话，就需要把你的`DDMCookieStore#saveDdmCookie` 方法贴出来看看

**Comment by 932707629** [comment]
```
/**
     * 清除所有缓存
     * @param context
     * @return
     */
    public static boolean clearAllCache(Context context) {
        if (!deleteDir(context.getCacheDir())) {
            return false;
        }
        if (Environment.getExternalStorageState().equals(Environment.MEDIA_MOUNTED)) {
            if (context.getExternalCacheDir()!=null){
                return deleteDir(context.getExternalCacheDir());
            }
        }
        return true;
    }

    /**
     * 文件夹路径
     *
     * @param dir 文件夹
     * @return File
     */
    private static boolean deleteDir(File dir) {
        if (dir == null) {
            return false;
        }
        if (dir.isDirectory()) {
            String[] children = dir.list();
            if (children!=null){
                for (int i = 0; i < children.length; i++) {
                    boolean success = deleteDir(new File(dir, children[i]));
                    if (!success) {
                        return false;
                    }
                }
            }
        }
        return dir.delete();
    }
```
以上是清除缓存的代码。

**Comment by 932707629** [comment]
```

    public void saveDdmCookie(HttpUrl url, List<Cookie> cookies){
        final String host = url.host();
        if (memoryCache != null) { //开启了内存缓存，则将cookie写入内存
            memoryCache.put(host, cookies);
        }

        DiskLruCache diskCache = getDiskLruCache();
        if (diskCache != null) { //开启了磁盘缓存，则将cookie写入磁盘
            DiskLruCache.Editor editor = null;
            try {
                editor = diskCache.edit(md5(host));
                if (editor == null) {
                    return;
                }
                writeCookie(editor, cookies);
                editor.commit();
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                abortQuietly(editor);
            }
        }
    }
```
以上是`DDMCookieStore#saveDdmCookie`方法实现  就是复制的`CookieStore#saveCookie`里的代码

**Comment by liujingxing** [comment]
你删除`cookie`的方式不对，不能直接删除文件夹。需要调用`ICookieJar#removeXxx`方法删除cookie

**Comment by 932707629** [comment]
> 你删除`cookie`的方式不对，不能直接删除文件夹。需要调用`ICookieJar#removeXxx`方法删除cookie

就是说清除缓存的时候要先移除cookie然后再清除缓存是吧   明白了  谢谢大佬
