### ISSUE TITLE
上传文件时，若文件名包含#号，会导致 StringIndexOutOfBoundsException 异常

### ISSUE THREAD

**Issue by licheedev** [liujingxing/okhttp-RxHttp#187]
使用的rxhttp版本是 2.4.0，Android版本是7.1.2

当上传的文件包含 `#` 号，比如 `1605593802946#666620201117141641709.mp4` ，上传时会导致异常，
异常信息：

```
    java.lang.StringIndexOutOfBoundsException: length=39; regionStart=36; regionLength=-23
        at java.lang.String.substring(String.java:1931)
        at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
        at java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1391)
        at rxhttp.wrapper.utils.BuildUtil.getMediaType(BuildUtil.java:96)
        at rxhttp.wrapper.param.IPart.addFile(IPart.java:49)
        at rxhttp.wrapper.param.IFile.addFile(IFile.java:26)
        at rxhttp.wrapper.param.IFile.addFile(IFile.java:22)
        at rxhttp.RxHttpFormParam.addFile(RxHttpFormParam.java:76)
        at com.abcxyz.app.repository.http.HttpApi.syncUpload(HttpApi.kt:113)
        at com.abcxyz.app.usercase.Operator.handle(Operator.kt:352)
        at com.abcxyz.app.usercase.Operator.dispatchTcpData(Operator.kt:98)
        at com.abcxyz.app.usercase.Cupboard$2.invoke(Cupboard.kt:32)
        at com.abcxyz.app.usercase.Cupboard$2.invoke(Cupboard.kt:15)
        at com.abcxyz.app.repository.tcp.TcpManager$tcpHandler$1$receiver$1$1.invokeSuspend(TcpManager.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by liujingxing** [comment]
更新版本，该问题在2.4.1版本已解决，当前最新版本2.4.3
