### ISSUE TITLE
Rxhttp 作为lib  解析{"msg":"server error","code":500,"data":{}}  异常

### ISSUE THREAD

**Issue by justin1213** [liujingxing/okhttp-RxHttp#213]
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at com.example.apirequest.parse.ResponseParser.onParse(ResponseParser.java:68)
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at rxhttp.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:105)
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at rxhttp.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:56)
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at rxhttp.ObservableCallEnqueue$HttpDisposable.onResponse(ObservableCallEnqueue.java:79)
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at java.lang.Thread.run(Thread.java:919)
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err: java.lang.NullPointerException: The onParse function returned a null value.
2021-01-16 21:26:11.806 19153-4072/com.zhongri.ppss W/System.err:     at java.util.Objects.requireNonNull(Objects.java:228)
2021-01-16 21:26:11.807 19153-4072/com.zhongri.ppss W/System.err:     at rxhttp.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:105)
2021-01-16 21:26:11.807 19153-4072/com.zhongri.ppss W/System.err:     at rxhttp.ObservableParser$SyncParserObserver.onNext(ObservableParser.java:56)
2021-01-16 21:26:11.807 19153-4072/com.zhongri.ppss W/System.err:     at rxhttp.ObservableCallEnqueue$HttpDisposable.onResponse(ObservableCallEnqueue.java:79)
2021-01-16 21:26:11.807 19153-4072/com.zhongri.ppss W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
2021-01-16 21:26:11.807 19153-4072/com.zhongri.ppss W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-01-16 21:26:11.807 19153-4072/com.zhongri.ppss W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-01-16 21:26:11.807 19153-4072/com.zhongri.ppss W/System.err:     at java.lang.Thread.run(Thread.java:919)

**Comment by liujingxing** [comment]
解析器里不能返回null对象
