### ISSUE TITLE
关于没有实体的返回数据

### ISSUE THREAD

**Issue by Joslyn-Chen** [liujingxing/okhttp-RxHttp#218]
首先这个库很好。
有的接口只需要code或者message，并不需要T，比如：
`
public class Response<T> {
    private int    code;
    private String msg;
    private T      data;
}
`
T有可能为空，但是AbstractParser<T>里面T又不能为空，只能抛出异常。这种情况怎么处理？
另外，使用moshi-kotlin-codegen解析这种，也会导致异常：
`java.lang.IllegalArgumentException: No JsonAdapter for T (with no annotations)`

**Comment by liujingxing** [comment]
[不需要T的情况点击这里](https://github.com/liujingxing/okhttp-RxHttp/wiki/FAQ#10%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E4%B8%8D%E8%A7%84%E8%8C%83%E5%AF%BC%E8%87%B4%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8)；
第二个moshi解析问题，是你的配置有问题，你再查查。

**Comment by Joslyn-Chen** [comment]
已经解决。
`open class ApiResponseParser<R> : Parser<ApiResponse<R>> {

  override fun onParse(response: Response): ApiResponse<R> {
    val body = ExceptionHelper.throwIfFatal(response)
    body.use {
      val mType = TypeUtil.getActualTypeParameter(javaClass, 0) // 当前泛型类型
      val type: Type = ParameterizedTypeImpl[ApiResponse::class.java, mType] //ApiResponse类型
      return response.convert(type)
    }
  }

}`
自定义了返回类型，不过这样只能用inline了。

**Comment by liujingxing** [comment]
不在解析器里统一判断code的话，这样写没有任何意义，`toClass<ApiResponse<T>>`方法就可以搞定

**Comment by Joslyn-Chen** [comment]
统一判断我放到了后面的协程里，想的是把请求和统一判断分开。使用toClass解析会出一个异常java.lang.AssertionError: illegal type variable reference，自定义就没问题

**Comment by liujingxing** [comment]
那这样判断code不是每次都要写？另外，toClass错误详情发出来看看，代码也发下

**Comment by Joslyn-Chen** [comment]
我这边的请求流程是这样的：
`(请求)->[请求工具]->[异步](code判断)->(LiveData)`
添加一个拓展方法就可以统一判断code了，并不影响请求工具和异步。
返回ApiResponse<R>，不管R是什么类型，一样可以正常获取code或者msg。
toClass错误（moshi-kotlin-codegen解析）：
`inline fun <reified R> postJson(request: BaseRequest): IAwait<ApiResponse<R>> {
  return RxHttp.postJson(request.requestUrl())
    .addAll(request.toJson())
    .toClass()
}`
`java.lang.AssertionError: illegal type variable reference
    at libcore.reflect.TypeVariableImpl.resolve(TypeVariableImpl.java:110)
    at libcore.reflect.TypeVariableImpl.getGenericDeclaration(TypeVariableImpl.java:124)
    at libcore.reflect.TypeVariableImpl.hashCode(TypeVariableImpl.java:47)
    at java.util.Arrays.hashCode(Arrays.java:1261)
    at com.squareup.moshi.internal.Util$ParameterizedTypeImpl.hashCode(Util.java:423)
    at java.util.Collections.secondaryHash(Collections.java:3405)
    at java.util.LinkedHashMap.get(LinkedHashMap.java:250)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:128)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:74)
    at rxhttp.wrapper.converter.MoshiConverter.convert(MoshiConverter.java:95)
    at rxhttp.wrapper.utils.Converter.convert(Converter.kt:21)
    at rxhttp.wrapper.parse.SimpleParser.onParse(SimpleParser.kt:20)
    at rxhttp.wrapper.utils.CallKt$await$$inlined$suspendCancellableCoroutine$lambda$3.onResponse(Call.kt:44)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)`

**Comment by liujingxing** [comment]
哈哈，你这个是kotlin的bug，刚写了篇文章介绍这个bug，你看看https://juejin.cn/post/6921359126438084621

**Comment by Joslyn-Chen** [comment]
那现阶段就只能用自定义的了
