### ISSUE TITLE
Actually not, but can't throw other exceptions due to RS

### ISSUE THREAD

**Issue by Jasperben** [liujingxing/okhttp-RxHttp#234]
Caused by: java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
        at io.reactivex.Observable.subscribe(Observable.java:12276)
        at rxhttp.wrapper.param.ObservableParser.subscribeActual(ObservableParser.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableDetach.subscribeActual(ObservableDetach.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at com.rxjava.rxlife.ObservableLife.subscribeActual(ObservableLife.java:90)
        at com.rxjava.rxlife.ObservableLife.subscribe(ObservableLife.java:70)
        at com.rxjava.rxlife.ObservableLife.subscribe(ObservableLife.java:56)
        at com.rxjava.rxlife.ObservableLife.subscribe(ObservableLife.java:39)

**Comment by liujingxing** [comment]
https://github.com/liujingxing/okhttp-RxHttp/issues/235
