### ISSUE TITLE
这个异常是什么原因

### ISSUE THREAD

**Issue by Jasperben** [liujingxing/okhttp-RxHttp#235]
java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2944)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3079)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
     Caused by: java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
        at io.reactivex.Observable.subscribe(Observable.java:12276)
        at rxhttp.wrapper.param.ObservableParser.subscribeActual(ObservableParser.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableDetach.subscribeActual(ObservableDetach.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at com.rxjava.rxlife.ObservableLife.subscribeActual(ObservableLife.java:90)
        at com.rxjava.rxlife.ObservableLife.subscribe(ObservableLife.java:70)
        at com.rxjava.rxlife.ObservableLife.subscribe(ObservableLife.java:56)
        at com.rxjava.rxlife.ObservableLife.subscribe(ObservableLife.java:39)

**Comment by liujingxing** [comment]
看看是不是你解析器返回null了

**Comment by Jasperben** [comment]
RxHttp.get(url)
                .asClass(DeviceBean.class)
                .as(RxLife.asOnMain(this))
                .subscribe(dataBean -> {
                
你是说dataBean是null吗

**Comment by liujingxing** [comment]
上面就是会触发异常的代码？

**Comment by Jasperben** [comment]
发现与url有关系
有问题的url是这样的http://:/report/getAccessDevice?sn=101021022450055
正常的url是这样的http://192.168.1.9:80/report/getAccessDevice?sn=101021022450055

**Comment by liujingxing** [comment]
那就是你的baseurl 拼接有问题，查查看。
