### ISSUE TITLE
demo会抛异常

### ISSUE THREAD

**Issue by hoopslb** [liujingxing/okhttp-RxHttp#48]
W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
W/System.err: java.net.SocketException: Socket closed
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
W/System.err:     at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:51)
W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:423)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at rxhttp.wrapper.progress.ProgressResponseBody$1.read(ProgressResponseBody.java:86)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
W/System.err:     at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
        at rxhttp.ObservableDownload.subscribeActual(ObservableDownload.java:85)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
E/RxHttp: java.net.SocketException: Socket closed
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258049386
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketException: Socket closed
D/RxHttp: <------------------- request start Method=GET ------------------->
    
    http://s9.pstatp.com/package/apk/aweme/app_aweGW_v6.6.0_2905d5c.apk?versionName=1.0.0&time=1577258055142
    
    RANGE: bytes=0-
    deviceType: android
W/System.err: rxhttp.wrapper.exception.HttpStatusCodeException: Method=GET Code=404
W/System.err: message = Not Found
    http://s9.pstatp.com/package/apk/aweme/app_aweGW_v6.6.0_2905d5c.apk?versionName=1.0.0&time=1577258055142
    Date: Wed, 25 Dec 2019 07:14:16 GMT
    Content-Type: text/html
    Content-Length: 169
    Connection: keep-alive
W/System.err: Server: nginx
    Vary: Accept-Encoding
    Vary: Accept-Encoding
    server-timing: inner; dur=100
    X-Ser: BC178_dx-lt-yd-jiangsu-zhenjiang-3-cache-4, BC10_dx-hainan-haikou-5-cache-4
    X-Cache: MISS from BC10_dx-hainan-haikou-5-cache-4(baishan)
    <html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
W/System.err: <hr><center>nginx/1.9.10</center>
    </body>
    </html>
W/System.err:     at rxhttp.wrapper.exception.ExceptionHelper.throwIfFatal(ExceptionHelper.java:29)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:36)
        at rxhttp.ObservableDownload.subscribeActual(ObservableDownload.java:85)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
E/RxHttp: rxhttp.wrapper.exception.HttpStatusCodeException: Method=GET Code=404
    message = Not Found
    
    http://s9.pstatp.com/package/apk/aweme/app_aweGW_v6.6.0_2905d5c.apk?versionName=1.0.0&time=1577258055142
    
    Date: Wed, 25 Dec 2019 07:14:16 GMT
    Content-Type: text/html
    Content-Length: 169
    Connection: keep-alive
    Server: nginx
    Vary: Accept-Encoding
    Vary: Accept-Encoding
    server-timing: inner; dur=100
    X-Ser: BC178_dx-lt-yd-jiangsu-zhenjiang-3-cache-4, BC10_dx-hainan-haikou-5-cache-4
    X-Cache: MISS from BC10_dx-hainan-haikou-5-cache-4(baishan)
    
    <html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.9.10</center>
    </body>
    </html>
D/RxHttp: <------------------- request start Method=GET ------------------->
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258056820
    
    RANGE: bytes=0-
    deviceType: android
W/System.err: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:384)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at rxhttp.wrapper.progress.ProgressResponseBody$1.read(ProgressResponseBody.java:86)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
W/System.err:     at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
        at rxhttp.ObservableDownload.subscribeActual(ObservableDownload.java:85)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
E/RxHttp: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
    
    https://apk-ssl.tancdn.com/3.5.3_276/探探.apk?versionName=1.0.0&time=1577258050199
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
I/RxHttp: <------------------- request end Method=GET Code=206 ------------------->(583ms)
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258056820
    
    Date: Wed, 25 Dec 2019 07:14:17 GMT
    Content-Type: application/vnd.android.package-archive
    Content-Length: 45419415
    Connection: keep-alive
    ETag: "637429375"
    Accept-Ranges: bytes
    Last-Modified: Mon, 02 Sep 2019 02:39:03 GMT
    Server: WS CDN Server
    Content-Range: bytes 0-45419414/45419415
    Age: 432372
    X-Via: 1.1 PS-000-0102761:3 (Cdn Cache Server V2.0)[27 200 0], 1.1 PS-000-01QNz36:0 (Cdn Cache Server V2.0)[47 200 0]
    
    /storage/emulated/0/Android/data/com.example.rxhttp/cache/4.apk
W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
D/RxHttp: <------------------- request start Method=GET ------------------->
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258063385
    
    RANGE: bytes=1075316-
    deviceType: android
I/RxHttp: <------------------- request end Method=GET Code=206 ------------------->(346ms)
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258063385
    
    Date: Wed, 25 Dec 2019 07:14:24 GMT
    Content-Type: application/vnd.android.package-archive
    Content-Length: 44344099
    Connection: keep-alive
    ETag: "637429375"
    Accept-Ranges: bytes
    Last-Modified: Mon, 02 Sep 2019 02:39:03 GMT
    Server: WS CDN Server
    Content-Range: bytes 1075316-45419414/45419415
    Age: 432378
    X-Via: 1.1 PS-000-0102761:3 (Cdn Cache Server V2.0)[27 200 0], 1.1 PS-000-01QNz36:0 (Cdn Cache Server V2.0)[0 200 0]
    
    /storage/emulated/0/Android/data/com.example.rxhttp/cache/0.apk
W/System.err: java.net.SocketException: Socket closed
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at okio.Okio$2.read(Okio.java:140)
W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:423)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
W/System.err:     at rxhttp.wrapper.progress.ProgressResponseBody$1.read(ProgressResponseBody.java:86)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
        at rxhttp.ObservableDownload.subscribeActual(ObservableDownload.java:85)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: java.net.SocketException: Socket closed
E/RxHttp: java.net.SocketException: Socket closed
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258056820
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketException: Socket closed
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
W/System.err:     at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:423)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at rxhttp.wrapper.progress.ProgressResponseBody$1.read(ProgressResponseBody.java:86)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
W/System.err:     at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
        at rxhttp.ObservableDownload.subscribeActual(ObservableDownload.java:85)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: java.net.SocketException: Socket closed
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:423)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at rxhttp.wrapper.progress.ProgressResponseBody$1.read(ProgressResponseBody.java:86)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
W/System.err:     at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
        at rxhttp.ObservableDownload.subscribeActual(ObservableDownload.java:85)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
E/RxHttp: java.net.SocketException: Socket closed
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258063385
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketException: Socket closed
E/RxHttp: java.net.SocketException: Socket closed
    
    https://o8g2z2sa4.qnssl.com/android/momo_8.18.5_c1.apk?versionName=1.0.0&time=1577258050949
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketException: Socket closed
W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
W/InputTransport: Slow Input: 119ms so far, channel 'ClientState{24834ca uid 10314 pid 15215} (server)' publisher ~ publishKeyEvent: seq=1, deviceId=-1, source=0x101, action=0x0, flags=0x8, keyCode=4, scanCode=0, metaState=0x0, repeatCount=0,downTime=30690986000000, eventTime=30690986000000
W/InputTransport: Slow Input: 146ms so far, channel 'ClientState{24834ca uid 10314 pid 15215} (server)' publisher ~ publishKeyEvent: seq=2, deviceId=-1, source=0x101, action=0x1, flags=0x8, keyCode=4, scanCode=0, metaState=0x0, repeatCount=0,downTime=30690986000000, eventTime=30690986000000
W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
W/System.err: java.net.SocketException: Socket closed
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:423)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
W/System.err:     at rxhttp.wrapper.progress.ProgressResponseBody$1.read(ProgressResponseBody.java:86)
W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
W/System.err:     at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
        at rxhttp.ObservableDownload.subscribeActual(ObservableDownload.java:85)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: java.net.SocketException: Socket closed
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:423)
W/System.err:     at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at rxhttp.wrapper.progress.ProgressResponseBody$1.read(ProgressResponseBody.java:86)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
W/System.err:     at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
W/System.err:     at rxhttp.ObservableDownload.subscribeActual(ObservableDownload.java:85)
W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: java.net.SocketException: Socket closed
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:423)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:19)
        at rxhttp.ObservableHttp.execute(ObservableHttp.java:116)
        at rxhttp.ObservableHttp.subscribeActual(ObservableHttp.java:67)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:423)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
W/System.err:     at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:124)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:112)
        at rxhttp.wrapper.utils.IOUtil.write(IOUtil.java:90)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:39)
E/RxHttp: java.net.SocketException: Socket closed
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258041863
W/System.err:     at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.java:19)
        at rxhttp.ObservableHttp.execute(ObservableHttp.java:116)
        at rxhttp.ObservableHttp.subscribeActual(ObservableHttp.java:67)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketException: Socket closed
W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
E/RxHttp: java.net.SocketException: Socket closed
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258022632
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketException: Socket closed
E/RxHttp: java.net.SocketException: Socket closed
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258044725
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketException: Socket closed
E/RxHttp: java.net.SocketException: Socket closed
    
    http://update.9158.com/miaolive/Miaolive.apk?versionName=1.0.0&time=1577258032205
E/RxJava: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketException: Socket closed
Process 15215 terminated.

**Comment by liujingxing** [comment]
页面销毁，关闭请求，抛异常走RxJava全局错误回调，没崩溃就是正常的

**Comment by lovemianhuatang** [comment]
RxJava全局错误回调需要我们自己定义还是内部已经定义了？

**Comment by liujingxing** [comment]
@lovemianhuatang 1.1.7版本后，内部会注册rxjava全局异常回调，内部收到回调，只会打印日志。详情请查看https://github.com/liujingxing/okhttp-RxHttp/blob/master/rxhttp/src/main/java/rxhttp/HttpSender.java
