### ISSUE TITLE
文件下载还是有问题

### ISSUE THREAD

**Issue by qinlang122** [liujingxing/okhttp-RxHttp#95]
下载的代码：
//val url = "https://qd.appdown.info/qd/androidtui/qd/tongbutui_v2.1.0_PCgw.apk"
val url = "https://static.newcger.com/uploads/preview/ae/2020/04/33056.mp4"

GlobalScope.launch {
            RxHttp.patchForm(url)
                    .setRangeHeader(progree, true)
                    .toDownload(path, this) {
                        val p = it.progress
                        val c = it.currentSize
                        val t = it.totalSize

                        Log.e("QL", "------>>$p $c $t")
                    }.await()
        }

换了不同的资源，要么就是404，405，501错误，要么就是一直超时，没有下载成功过。同样的资源。纯retrofit+okhttp写的和浏览器都能正常下载。

报错：
--------- beginning of crash
2020-04-21 09:43:30.967 6774-6804/com.qlang.mydemo E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.qlang.mydemo, PID: 6774
    rxhttp.wrapper.exception.HttpStatusCodeException: Method=PATCH Code=405
    message = Not Allowed
    
    https://static.newcger.com/uploads/preview/ae/2020/04/33056.mp4
    
    
    
    Server: Apache/1.12.2
    Date: Tue, 21 Apr 2020 01:43:22 GMT
    Content-Type: text/html
    Content-Length: 174
    Connection: keep-alive
    
    <html>
    <head><title>405 Not Allowed</title></head>
    <body bgcolor="white">
    <center><h1>405 Not Allowed</h1></center>
    <hr><center>Apache/1.12.2</center>
    </body>
    </html>
    
        at rxhttp.wrapper.exception.ExceptionHelper.throwIfFatal(ExceptionHelper.java:33)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.kt:26)
        at rxhttp.wrapper.parse.DownloadParser.onParse(DownloadParser.kt:15)
        at rxhttp.wrapper.await.AwaitImpl$await$$inlined$suspendCancellableCoroutine$lambda$2.onSuccess(AwaitImpl.kt:114)
        at rxhttp.wrapper.await.AwaitImpl$await$$inlined$suspendCancellableCoroutine$lambda$2.onResponse(AwaitImpl.kt:95)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by liujingxing** [comment]
提示很明确了，PATCH方法不被允许，请用get方法下载

**Comment by qinlang122** [comment]
额，这代码可是你文章里面写的。https://juejin.im/post/5e77604fe51d4527066eb81a#heading-13

val localPath = "sdcard//android/data/..../1.apk"                        
val student = RxHttp.postForm("/service/...")                            
    .setRangeHeader(1000, 300000)   //断点下载，设置下载起始/结束位置                                     
    .toDownload(localPath, this) { //此this为CoroutineScope对象           
        //it为Progress对象                                                  
        val process = it.progress        //已下载进度 0-100                          
        val currentSize = it.currentSize //已下size，单位：byte               
        val totalSize = it.totalSize     //要下的总size 单位：byte                 
    }      
    .await()

**Comment by liujingxing** [comment]
抱歉，笔误，已修改
